/*ADMIN TABLE*/
CREATE TABLE ADMIN(
    NAME VARCHAR(255),
    EMAIL VARCHAR(320),
    AGE SMALLINT,
    PHONE VARCHAR(10),
    GENDER VARCHAR(10),
    PASSWORD VARCHAR(255),
    PROFILE VARCHAR(255)
) ENGINE=InnoDB;

/*ADD CHECK IN GENDER*/
ALTER TABLE ADMIN ADD CONSTRAINT CHECK_GENDER_ADMIN CHECK(UCASE(GENDER) IN ('MALE', 'FEMALE'));


/*ADD PRIMARY KEY*/
ALTER TABLE ADMIN ADD CONSTRAINT pk_admin PRIMARY KEY (NAME, EMAIL, PHONE);


/*EMPLOYEE TABLE*/
CREATE TABLE EMPLOYEE(
    NAME VARCHAR(255),
    EMAIL VARCHAR(320),
    AGE SMALLINT,
    PHONE VARCHAR(10),
    GENDER VARCHAR(10),
    PASSWORD VARCHAR(255),
    PROFILE VARCHAR(255)
) ENGINE=InnoDB;

-- ADD CHECK IN GENDER
ALTER TABLE EMPLOYEE ADD CONSTRAINT CHECK_GENDER_EMP CHECK(UCASE(GENDER) IN ('MALE', 'FEMALE'));


/*ADD PRIMARY KEY*/
ALTER TABLE EMPLOYEE ADD CONSTRAINT pk_employee PRIMARY KEY (NAME, EMAIL, PHONE);



/*INSERT ADMIN RECORD*/
INSERT INTO ADMIN VALUES('MINT@123','MINT123@gmail.com',19,'8248929308','MALE','$2y$10$If7fyvI8vcaFdUhFzD3MVueUYYi1Yd2XgLzxkC4.xJdRXxnCoc3sa','user.png');

/*INSERT EMPLOYEE RECORD*/
INSERT INTO EMPLOYEE VALUES('Nalan','nalanpandimadurai@gmail.com',19,'8248929308','MALE','$2y$10$2Xj0iY6aWQ41B0sutaRq1egZjxe4O7EFUdKOk44vsW6GBIN3NkxkC','user.png');
INSERT INTO EMPLOYEE VALUES('Irfan','irfan123@gmail.com',19,'8778321216','MALE','$2y$10$qfz9TpP2h/YcPuFhU3cfiOJa9peZCzQkJyJhnYHXwbJhuU1cYIcxW','user.png');
INSERT INTO EMPLOYEE VALUES('Muthu','muthu123@gmail.com',19,'9550931366','MALE','$2y$10$RGm.VePq1YYeIoEh9m.XzOjR7ANK.bBOlwfm.9OuddQWbVBEBSH1O','user.png');
INSERT INTO EMPLOYEE VALUES('Tarun','tarun123@gmail.com',19,'9092903899','MALE','$2y$10$OAmWvQZ7VHxcOrg7DiScq.Fu9viRsZKEYrc2JIV/dfaORW.JYBc7u','user.png');


/* TASKS TABLE */

CREATE TABLE Tasks (
    EmployeeName VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    FOREIGN KEY (EmployeeName) REFERENCES EMPLOYEE(NAME) ON DELETE CASCADE
) ENGINE=InnoDB;

