/*ADMIN TABLE*/
CREATE TABLE ADMIN(
    NAME VARCHAR(255),
    EMAIL VARCHAR(320),
    AGE SMALLINT,
    PHONE VARCHAR(10),
    GENDER VARCHAR(10),
    PASSWORD VARCHAR(255),
    PROFILE VARCHAR(255)
) ENGINE=InnoDB;

/*ADD CHECK IN GENDER*/
ALTER TABLE ADMIN ADD CONSTRAINT CHECK_GENDER_ADMIN CHECK(UCASE(GENDER) IN ('MALE', 'FEMALE'));

/*ADD UNIQUE KEY*/
ALTER TABLE ADMIN ADD CONSTRAINT ADMIN_UNIQUE UNIQUE(NAME, EMAIL, PHONE);

/*EMPLOYEE TABLE*/
CREATE TABLE EMPLOYEE(
    NAME VARCHAR(255),
    EMAIL VARCHAR(320),
    AGE SMALLINT,
    PHONE VARCHAR(10),
    GENDER VARCHAR(10),
    PASSWORD VARCHAR(255),
    PROFILE VARCHAR(255)
) ENGINE=InnoDB;

-- ADD CHECK IN GENDER
ALTER TABLE EMPLOYEE ADD CONSTRAINT CHECK_GENDER_EMP CHECK(UCASE(GENDER) IN ('MALE', 'FEMALE'));

/* ADD UNIQUE KEY*/
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_UNIQUE UNIQUE(NAME, EMAIL, PHONE);


/*INSERT ADMIN RECORD*/
INSERT INTO ADMIN VALUES('MINT@123','MINT123@gmail.com',19,'8248929308','MALE','$2y$10$If7fyvI8vcaFdUhFzD3MVueUYYi1Yd2XgLzxkC4.xJdRXxnCoc3sa','user.png');

/*INSERT EMPLOYEE RECORD*/
INSERT INTO EMPLOYEE VALUES('Nalan','nalanpandimadurai@gmail.com',19,'8248929308','MALE','$2y$10$2Xj0iY6aWQ41B0sutaRq1egZjxe4O7EFUdKOk44vsW6GBIN3NkxkC','user.png');